export enum UserRole {
  ADMIN = "ADMIN",

  REGISTRAR = "REGISTRAR",

  DEPARTMENT_HEAD = "DEPARTMENT_HEAD",

  TEACHER = "TEACHER",

  ACCOUNTANT = "ACCOUNTANT",

  EXAM_CONTROLLER = "EXAM_CONTROLLER",

  LIBRARIAN = "LIBRARIAN",

  STUDENT = "STUDENT",
}

export enum Gender {
  MALE = "MALE",
  FEMALE = "FEMALE",
  OTHER = "OTHER",
}